access-token:
  private: "access-refresh-token-keys/access-token-private.key"
  public: "access-refresh-token-keys/access-token-public.key"
refresh-token:
  private: "access-refresh-token-keys/refresh-token-private.key"
  public: "access-refresh-token-keys/refresh-token-public.key"
spring:
  data:
    mongodb:
      uri: mongodb+srv://asel:asel2003@cluster1.fklvjxr.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1
      database: test

app:
  secret:
    key: "secret"